print("=== Secret Code Generator ===")

message= input('Write your secret message :- ').lower()

secret = message.replace('a','!')
secret = secret.replace('b','1')
secret = secret.replace('c','@')
secret = secret.replace('d','2')
secret = secret.replace('e','#')
secret = secret.replace('z','3')
secret = secret.replace('y','$')
secret = secret.replace('x','4')
secret = secret.replace('w','%')
secret = secret.replace('v','5')
secret = secret.replace('u','^')
secret = secret.replace('i','6')
secret = secret.replace('o','&')
secret = secret.replace('u','7')
secret = secret.replace('j','!)')
secret = secret.replace('f',')^')
secret = secret.replace('k','0#')
secret = secret.replace('t','@0')
secret = secret.replace('o','!%')
secret = secret.replace('p','1^')
secret = secret.replace('m','!#')
secret = secret.replace('q','9')

print('your encoded message is :- ')
print(secret)